### ISSUE TITLE
Indicate bundles without manager plugin

### ISSUE THREAD

**Issue by fbender** [contao/managed-edition#2]
(Not exactly sure if this is the right spot here – the issue applies to the Contao Manager as well. Please advise on moving the issue.)

Considering that extension bundles require a "manager plugin" to work out-of-the-box when installed through the Contao Manager, the managed edition should somehow indicate if a bundle does not contain the required manager plugin (i.e. if the admin needs to perform manual steps to get an extension to work). This should both be handled in the Contao Manager and `composer` directly (if possible) as well as any other Contao-specific installation method.

If on the other hand the Contao Manager only lists bundles that contain the required manager plugin, this issue is nil.

**Comment by aschempp** [comment]
The idea is to only allow installation of extensions with plugins in the UI, but your point is still valid for the command line. I think it should be possible to add a warning or similar.

**Comment by filipbasara** [comment]
Does the managed version allow the installation via Contao Manager yet? If yes, how would one do so?

**Comment by aschempp** [comment]
@filipbasara The Contao Manager (UI) is not available yet.

**Comment by aschempp** [comment]
@fbender so the UI will mark bundles that are not compatible. Installing a bundle on the command line will not show a warning though, but I wonder if that's actually necessary? Using the command line is an advanced interface, and one should be aware whether the bundle can run or not?

Also, since version 4.3.5, all Contao 3 extensions (in system/modules) are enabled automatically, meaning this only applies to Symfony bundles and Contao 4 bundles without plugin. I don't think it makes sense to show a warning for Symfony bundles, and having a composer plugin for the (hopefully) rare case seems rather unnecessary to me? Would you agree (and close the ticket)?

**Comment by aschempp** [comment]
closing due to no feedback.
